### ISSUE TITLE
喵上漫画下载图片异常

### ISSUE THREAD

**Issue by iewoai** [xsk666/my_reverse_projects#2]
喵上漫画的图片下载出来是“检测到环境异常...”，可能是版本问题导致的。

**Comment by xsk666** [comment]
刚才简单看了一下，现在多了`psign`和`sign1`，难度应该不大。如果你有能力的话可以自己尝试一下，不会脱壳的话，加我qq:3104182180

**Comment by xsk666** [comment]
已修复，教程地址：[52破解](https://www.52pojie.cn/thread-1840995-1-1.html)
